# Generated by Django 4.2 on 2024-07-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("coaching", "Coaching"),
                            ("entrenamientos", "Entrenamientos"),
                            ("dinamicas", "Dinámicas"),
                        ],
                        max_length=40,
                    ),
                ),
                ("camada", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NivelDeAprendizaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=40)),
                (
                    "experiencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentores",
                        to="myapp1.experiencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=40)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("aprendiz", "Aprendiz"),
                            ("alquimista", "Alquimista"),
                        ],
                        default="iniciado",
                        max_length=10,
                    ),
                ),
                (
                    "experiencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprendices",
                        to="myapp1.experiencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("fecha_de_entrega", models.DateField()),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="myapp1.aprendiz",
                    ),
                ),
                (
                    "experiencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="myapp1.experiencia",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="myapp1.niveldeaprendizaje",
                    ),
                ),
            ],
        ),
    ]
