# Generated by Django 4.2 on 2024-08-10 02:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencia",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AddField(
            model_name="experiencia",
            name="duracion",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="experiencia",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experiencia",
            name="ubicacion",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
    ]
