# Generated by Django 4.2 on 2024-08-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0002_experiencia_descripcion_experiencia_duracion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencia",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="duracion",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
