# Generated by Django 4.2 on 2024-08-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0003_alter_experiencia_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprendiz",
            name="experiencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp1.experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("iniciado", "Iniciado"),
                    ("aprendiz", "Aprendiz"),
                    ("alquimista", "Alquimista"),
                ],
                max_length=10,
            ),
        ),
    ]
