# Generated by Django 4.2 on 2024-08-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0004_alter_aprendiz_experiencia_alter_aprendiz_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprendiz",
            name="experiencia",
            field=models.CharField(max_length=40),
        ),
    ]
