# Generated by Django 4.2 on 2024-08-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0005_alter_aprendiz_experiencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="experiencia",
            field=models.CharField(
                choices=[
                    ("basico", "Básico"),
                    ("intermedio", "Intermedio"),
                    ("experto", "Experto"),
                ],
                max_length=10,
            ),
        ),
    ]
