# Generated by Django 4.2 on 2024-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0006_alter_mentor_experiencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencia",
            name="camada",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
