# Generated by Django 4.2 on 2024-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0007_alter_experiencia_camada"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
