# Generated by Django 4.2 on 2024-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0009_remove_actividad_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="aprendiz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="experiencia",
            field=models.CharField(default="Sin Experiencia", max_length=100),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nivel",
            field=models.CharField(default="Sin experiencia", max_length=100),
            preserve_default=False,
        ),
    ]
