# Generated by Django 4.2 on 2024-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp1",
            "0012_alter_actividad_aprendiz_alter_actividad_experiencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="niveldeaprendizaje",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="niveldeaprendizaje",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="niveldeaprendizaje",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01T00:00:00Z"
            ),
            preserve_default=False,
        ),
    ]
