# Generated by Django 4.2 on 2024-08-10 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0013_niveldeaprendizaje_activo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveldeaprendizaje",
            name="fecha_creacion",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
