# Generated by Django 4.2 on 2024-08-10 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0014_alter_niveldeaprendizaje_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveldeaprendizaje",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
