# Generated by Django 4.2 on 2024-08-10 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp1",
            "0016_alter_actividad_aprendiz_alter_actividad_experiencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="detalles",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="actividad",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="aprendiz",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="experiencia",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="fecha_de_entrega",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nivel",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
