# Generated by Django 4.2 on 2024-08-10 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0017_actividad_activo_actividad_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividad",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="detalles",
        ),
        migrations.RemoveField(
            model_name="actividad",
            name="fecha_creacion",
        ),
        migrations.AlterField(
            model_name="actividad",
            name="aprendiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp1.aprendiz"
            ),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="experiencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp1.experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="fecha_de_entrega",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nivel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp1.niveldeaprendizaje",
            ),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
