# Generated by Django 4.2 on 2024-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp1",
            "0018_remove_actividad_activo_remove_actividad_descripcion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="aprendiz",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="experiencia",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nivel",
            field=models.CharField(max_length=30),
        ),
    ]
